// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4JVjRQZbZTZC8BnoKLr7mrhk6lZ3kW8U',
    appId: '1:26352596770:web:40e155aceeda2104b9d77b',
    messagingSenderId: '26352596770',
    projectId: 'todolist-firebase-ff65f',
    authDomain: 'todolist-firebase-ff65f.firebaseapp.com',
    storageBucket: 'todolist-firebase-ff65f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHcIph8W6iXFeUkt3VxD071RyuX7t26rs',
    appId: '1:26352596770:android:4c95d8cc349c6b0cb9d77b',
    messagingSenderId: '26352596770',
    projectId: 'todolist-firebase-ff65f',
    storageBucket: 'todolist-firebase-ff65f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB83ZkAkt0PVntOJOnHGj3H9K5uKWyuzo',
    appId: '1:26352596770:ios:19ca739d920d6f34b9d77b',
    messagingSenderId: '26352596770',
    projectId: 'todolist-firebase-ff65f',
    storageBucket: 'todolist-firebase-ff65f.appspot.com',
    iosBundleId: 'com.example.todolistFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB83ZkAkt0PVntOJOnHGj3H9K5uKWyuzo',
    appId: '1:26352596770:ios:19ca739d920d6f34b9d77b',
    messagingSenderId: '26352596770',
    projectId: 'todolist-firebase-ff65f',
    storageBucket: 'todolist-firebase-ff65f.appspot.com',
    iosBundleId: 'com.example.todolistFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4JVjRQZbZTZC8BnoKLr7mrhk6lZ3kW8U',
    appId: '1:26352596770:web:da1e1c1e30aa98b8b9d77b',
    messagingSenderId: '26352596770',
    projectId: 'todolist-firebase-ff65f',
    authDomain: 'todolist-firebase-ff65f.firebaseapp.com',
    storageBucket: 'todolist-firebase-ff65f.appspot.com',
  );
}
